import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/ninebasic-api",
    },
    {
      type: "category",
      label: "agents",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-agents",
          label: "routes/atendentes.js",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-agents-breaks-email",
          label: "⏸️ Pausar atendimento",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-agents-heartbeat",
          label: "POST /api/v1/agents/heartbeat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-agents-heartbeat",
          label: "PUT /api/v1/agents/heartbeat",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-agents-presence-email",
          label: "POST /api/v1/agents/presence/{email}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-agents-presence-email",
          label: "PUT /api/v1/agents/presence/{email}",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-agents-resume-email",
          label: "▶️ Retomar da pausa",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-agents-session-email",
          label: "🔐 Abrir/atualizar sessão",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-agents-status-email",
          label: "GET /api/v1/agents/status/{email}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-api-v-1-agents-status-session",
          label: "PATCH /api/v1/agents/status/{session}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-agents-status-session",
          label: "POST /api/v1/agents/status/{session}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-agents-status-session",
          label: "PUT /api/v1/agents/status/{session}",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-agents-email",
          label: "🔍 Buscar atendente por email",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-agents-id",
          label: "🗑️ Excluir atendente",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "analytics",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-agents-realtime",
          label: "* ==========================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-abandonment",
          label: "* ==================================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-agents-art",
          label: "* ==================================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-aging-by-queue",
          label: "* ==================================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-duration-by-queue",
          label: "* ==================================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-analytics-metrics-feedback",
          label: "POST /metrics/feedback  -> salva NPS/CSAT",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-feedback-responses",
          label: "GET /api/v1/analytics/metrics/feedback/responses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-frt",
          label: "* ==================================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-new-clients",
          label: "GET /analytics/metrics/new-clients?group=day&from&to",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-queues",
          label: "* ==================================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-series-csat",
          label: "GET /metrics/series/csat -> série temporal para gráficos (com distribuição e gauge)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-series-nps",
          label: "GET /metrics/series/nps  -> série temporal para gráficos (com NPS e distribuição)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-metrics-summary",
          label: "GET /api/v1/analytics/metrics/summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-analytics-realtime",
          label: "* ==========================",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "billing",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-billing-pricing",
          label: "========== PRICING (public.billing_pricing) ==========",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-billing-pricing",
          label: "UPSERT de preço (por channel)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-billing-pricing-channel",
          label: "DELETE preço",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-billing-pricing-channel",
          label: "Buscar preço de um canal",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-api-v-1-billing-pricing-channel",
          label: "PATCH preço",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-billing-pricing-channel",
          label: "PUT preço",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-billing-statement",
          label: "========== EXTRATO AGREGADO (Geral por user_id+channel) ==========",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-billing-statement-daily",
          label: "========== EXTRATO DIÁRIO (Geral por dia+canal) ==========",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-billing-statement-detail",
          label: "========== DETALHE (lista cada sessão com preço) ==========",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "breaks",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-breaks",
          label: "routes/pausas.js",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-breaks",
          label: "Criar motivo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-breaks-agents-email-current",
          label: "========== SESSÕES DE PAUSA DO ATENDENTE ==========",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-breaks-agents-email-history",
          label: "Histórico do atendente",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-breaks-agents-email-start",
          label: "Iniciar pausa",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/patch-api-v-1-breaks-agents-email-id-end",
          label: "Encerrar pausa",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-breaks-id",
          label: "Remover motivo (só se não houver sessões vinculadas)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-breaks-id",
          label: "Buscar um motivo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-api-v-1-breaks-id",
          label: "Atualizar motivo (PATCH)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-breaks-id",
          label: "Atualizar motivo (PUT)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/patch-api-v-1-breaks-id-toggle",
          label: "Alternar ativo/inativo",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "campaigns",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-campaigns",
          label: "Retorna também agregados de campaign_items para progresso.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-campaigns",
          label: "status inicial: 'queued' (imediata) ou 'scheduled' (agendada)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-campaigns-id",
          label: "=============================================================================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-campaigns-id-items",
          label: "Para inspecionar itens; deixe comentado se não precisar agora.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "conversations",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-conversations",
          label: "routes/chatsRoutes.js",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-conversations-queues",
          label: "GET /api/v1/conversations/queues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-conversations-queues-next",
          label: "PUT /api/v1/conversations/queues/next",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "customers",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-customers",
          label: "GET /clientes?page=&page_size=&q=",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-customers-user-id",
          label: "DELETE /clientes/:user_id",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-customers-user-id",
          label: "GET /clientes/:user_id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-api-v-1-customers-user-id",
          label: "PATCH /clientes/:user_id",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-customers-user-id",
          label: "PUT /clientes/:user_id",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "flows",
      items: [
        {
          type: "doc",
          id: "api/post-api-v-1-flows-activate",
          label: "POST /api/v1/flows/activate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-flows-data-id",
          label: "GET /api/v1/flows/data/{id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-flows-history",
          label: "GET /api/v1/flows/history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-flows-latest",
          label: "GET /api/v1/flows/latest",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-flows-publish",
          label: "POST /api/v1/flows/publish",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-flows-sessions-user-id",
          label: "GET /api/v1/flows/sessions/{user_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-flows-sessions-user-id",
          label: "POST /api/v1/flows/sessions/{user_id}",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "messages",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-messages-check-24-h-user-id",
          label: "===================== STATUS / CONTAGEM =====================",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-messages-read-status",
          label: "GET /api/v1/messages/read-status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-messages-read-status-user-id",
          label: "PUT /api/v1/messages/read-status/:user_id",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-messages-send",
          label: "===================== ENVIO =====================",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-messages-send-template",
          label: "POST /api/v1/messages/send/template",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-messages-unread-counts",
          label: "GET /api/v1/messages/unread-counts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-messages-user-id",
          label: "===================== LISTAGEM =====================",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "queue-hours",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-queue-hours-queue-hours",
          label: "GET /queues/:queue/hours",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-queue-hours-queue-hours",
          label: "POST /queues/:queue/hours  (upsert)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-queue-hours-queue-hours",
          label: "PUT /queues/:queue/hours  (upsert — aceita weekly **ou** windows)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-queue-hours-queue-hours-test",
          label: "POST /queues/:queue/hours/test",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "queues",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-queues",
          label: "📥 Listar filas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-queues",
          label: "➕ Criar nova fila (ativa sempre TRUE; descricao/color opcionais)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-queues-agents-queue-name",
          label: "👥 Atendentes online da fila",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-queues-queues-permission",
          label: "🔄 Definir permissão de transferência",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-queues-queues-permission-email",
          label: "👀 Obter filas que o usuário pode transferir",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "quick-replies",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-quick-replies",
          label: "📄 Listar todas as respostas rápidas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-quick-replies",
          label: "routes/quickReplies.js",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-quick-replies-id",
          label: "🗑️ Remover uma resposta rápida",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "security",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-security-tokens",
          label: "Lista tokens do tenant (mascarados; sem segredo)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-security-tokens",
          label: "POST /security/tokens",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-security-tokens-id-revoke",
          label: "Revoga (não permite revogar o default)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "settings",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-settings",
          label: "Rota GET /settings - Retorna todas as configurações",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-settings",
          label: "Rota POST /settings - Cria ou atualiza uma configuração",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "storage",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-storage-presigned-url",
          label: "routes/uploadPresignedRoutes.js",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "telegram",
      items: [
        {
          type: "doc",
          id: "api/post-api-v-1-telegram-connect",
          label: "routes/telegram.js",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-telegram-status",
          label: "GET /api/v1/telegram/status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "templates",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-templates",
          label: "===== Rotas locais (DB do tenant) =====",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-templates",
          label: "POST / -> cria rascunho local (serializa JSONs)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-templates-provider",
          label: "GET /provider -> lista direto da Graph (inclui quality_score)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-templates-sync-all",
          label: "POST /sync-all -> importa/atualiza todos (serializa JSONs; sem ON CONFLICT duro)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-templates-id",
          label: "DELETE /:id -> remove local",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-templates-id-submit",
          label: "===== Rotas que falam com a Graph =====",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-templates-id-sync",
          label: "POST /:id/sync -> sincroniza status e quality_score (se houver coluna)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "tickets",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-tickets-history",
          label: "nada de client.release(); // << NÃO existe nesse client",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-tickets-history-id",
          label: "GET /api/v1/tickets/history/{id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-tickets-history-id-pdf",
          label: "Validação simples do formato do user_id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-tickets-last-user-id",
          label: "GET /tickets/last/:user_id → retorna o ticket mais recente do usuário",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-tickets-transferir",
          label: "POST /tickets/transferir → fecha atual e cria novo em outra fila",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-tickets-user-user-id",
          label: "GET /tickets/user/:user_id → tickets fechados do usuário",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-tickets-user-id",
          label: "GET /tickets/:user_id → Consulta ticket aberto por user_id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-tickets-user-id",
          label: "PUT /tickets/:user_id → fechar último ticket aberto do user_id e publicar evento",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "users",
      items: [
        {
          type: "doc",
          id: "api/get-api-v-1-users",
          label: "Listar",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-users",
          label: "Criar (tenant + public + invite)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-users-email",
          label: "Buscar por email",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-users-id",
          label: "Excluir (tenant) + chamada externa para remover em public.users",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-users-id",
          label: "Atualizar (sincroniza public.users: apenas profile)",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "whatsapp",
      items: [
        {
          type: "doc",
          id: "api/post-api-v-1-whatsapp-embedded-es-finalize",
          label: "============ FINALIZE (Embedded Signup) ============",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-whatsapp-embedded-es-pick-number",
          label: "routes/waEmbedded.js (trecho)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-whatsapp-number",
          label: "GET /wa/number -> metadados do número (UI)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-whatsapp-photo-from-url",
          label: "POST /wa/profile/photo-from-url -> upload + aplicar foto",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-whatsapp-profile",
          label: "---------- ENDPOINTS ----------",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-api-v-1-whatsapp-profile",
          label: "POST /wa/profile -> update about/address/description/email/vertical/websites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-api-v-1-whatsapp-profile-photo",
          label: "DELETE /wa/profile/photo -> remove foto",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-api-v-1-whatsapp-status",
          label: "GET /api/v1/whatsapp/status",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
